error: this exception can't be used because it's being used by the runtime
 --> $DIR/exception-systick-used.rs:6:8
  |
6 |     fn SysTick(_: SysTick::Context) {}
  |        ^^^^^^^

error: aborting due to previous error

